import Head from 'next/head'
import { Box, Container, Typography } from '@mui/material'
import { handlee, cormorant } from './../utils'

export default function Home() {
  return (
    <Container maxWidth='lg'>
      <Head>
        <title>Next + MUI Font Practice</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box component='header' p={2}>
        <Typography
          variant='h3'
          component='h1'
          align='center'
          sx={{
            fontFamily: handlee.style.fontFamily,
          }}
        >
          What a nice day!
        </Typography>
      </Box>
      <Box component='main' p={2}>
        <Typography
          variant='body1'
          component='p'
          align='center'
          sx={{
            fontFamily: cormorant.style.fontFamily,
          }}
        >
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat eos
          reiciendis molestiae deleniti sapiente, ratione dolorum sint
          aspernatur numquam corporis perferendis voluptates magnam laudantium
          libero molestias illo corrupti commodi nesciunt. Quidem iusto
          quisquam, ipsa aut unde impedit, quam voluptate sequi natus provident
          omnis soluta dicta illo sint porro pariatur asperiores, temporibus
          voluptatem possimus repudiandae est ex! Similique qui nam ipsum.
          Expedita, hic fugiat excepturi harum modi quaerat? Iste repudiandae
          est ipsam commodi aliquam, nam sunt laboriosam assumenda. Labore,
          debitis dolorum eos velit ipsum repudiandae dolor voluptatum
          doloremque eaque neque recusandae.
        </Typography>
      </Box>
    </Container>
  )
}
